# -*- coding: utf-8 -*-
"""purchasing_power_calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wl3-IWY95a4M5ihrWqa_mGFclu_59_TD
"""

savings = int(input(print("introduce savings amount: ")))
original_savings = savings
years = int(input(print("introduce years: ")))
inflation = float(input(print("introduce inflation rate as a float number: ")))
total_lost_purchasing_power = 0

for i in range(1, years + 1):
  lost_purchasing_power = (savings * (inflation/100))
  savings = (savings - lost_purchasing_power)
  total_lost_purchasing_power += lost_purchasing_power
  total_lost_purchasing_power_as_percentage = (total_lost_purchasing_power/original_savings)*100
  print("\n")
  print(f"Year: {i}")
  print(f"New savings: {savings}")
  print(f"Purchasing power lost in total: {total_lost_purchasing_power}")  
  print(f"Purchasing power lost in total as a percentage of your original savings: {total_lost_purchasing_power_as_percentage}%")

print(f"\n\nYou started with savings equal to: {original_savings}, over {years} years, you have lost a total of {total_lost_purchasing_power_as_percentage}% of purchasing power")